name: scaleflow_auth

description: "ScaleFlow - Login & Register screens (Mobile track task)"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/global.jpg
    - assets/images/Logo1.png
    - assets/images/Reg-Image.jpg
    - assets/images/Login-Image.jpg
    - assets/images/Dash-Image.jpg
    - assets/images/Home-Image.jpg
    - assets/images/Proj-Image.jpg
